name: Deploy to Google Cloud Kubernetes Engine

on: push

jobs:
  deploy:
    name: Deploy to Google Cloud Kubernetes Engine
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          version: "290.0.1"
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true
      - name: Login to docker hub
        uses: actions-hub/docker/login@master
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build Containers and Run Tests
        run: |
          docker build -t jackmckew/vue-test -f ./client/Dockerfile.dev ./client
          docker run -e CI=true jackmckew/vue-test npm test
      - name: Build Images
        run: |
          docker build -t jackmckew/multi-docker-client:latest -t jackmckew/multi-docker-client:${GITHUB_SHA} -f ./client/Dockerfile ./client
          docker build -t jackmckew/multi-docker-server:latest -t jackmckew/multi-docker-server:${GITHUB_SHA} -f ./server/Dockerfile ./server
          docker build -t jackmckew/multi-docker-worker:latest -t jackmckew/multi-docker-worker:${GITHUB_SHA} -f ./worker/Dockerfile ./worker

          - name: Push to Docker Hub multi-docker-client:latest
        uses: actions-hub/docker@master
        with:
          args: push jackmckew/multi-docker-client:latest
      - name: Push to Docker Hub multi-docker-server:latest
        uses: actions-hub/docker@master
        with:
          args: push jackmckew/multi-docker-server:latest
      - name: Push to Docker Hub multi-docker-worker:latest
        uses: actions-hub/docker@master
        with:
          args: push jackmckew/multi-docker-worker:latest

      - name: Push to Docker Hub multi-docker-client:${GITHUB_SHA}
        uses: actions-hub/docker@master
        with:
          args: push jackmckew/multi-docker-client:${GITHUB_SHA}
      - name: Push to Docker Hub multi-docker-server:${GITHUB_SHA}
        uses: actions-hub/docker@master
        with:
          args: push jackmckew/multi-docker-server:${GITHUB_SHA}
      - name: Push to Docker Hub multi-docker-worker:${GITHUB_SHA}
        uses: actions-hub/docker@master
        with:
          args: push jackmckew/multi-docker-worker:${GITHUB_SHA}

      - name: Update Kubernetes Configuration
        run: |
          kubectl apply -f k8s
          kubectl set image deployments/client-deployment client=jackmckew/multi-docker-client:${GITHUB_SHA}
          kubectl set image deployments/server-deployment server=jackmckew/multi-docker-server:${GITHUB_SHA}
          kubectl set image deployments/worker-deployment worker=jackmckew/multi-docker-worker:${GITHUB_SHA}
