name: Deploy to Google Cloud Kubernetes Engine

on: push

jobs:
  deploy:
    name: Deploy to Google Cloud Kubernetes Engine
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          version: "290.0.1"
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true
      - run: gcloud info
      - name: Login to docker hub
        uses: actions-hub/docker/login@master
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      - run: docker build -t jackmckew/vue-test -f ./client/Dockerfile.dev ./client
      - run: docker run -e CI=true jackmckew/vue-test npm test
